all_countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "The Democratic Republic of Congo",
    "Cook Islands",
    "Costa Rica",
    "Ivory Coast",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "England",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji Islands",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Isle of Man",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "North Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montserrat",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "Northern Ireland",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Korea",
    "South Sudan",
    "Spain",
    "SriLanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Islands, British",
    "Virgin Islands, U.S.",
    "Wales",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Yugoslavia",
    "Zambia",
    "Zimbabwe",
]

commonwealth_states = [
    "Antigua and Barbuda",
    "Australia",
    "Bahamas",
    "Bangladesh",
    "Barbados",
    "Belize",
    "Botswana",
    "Brunei",
    "Cameroon",
    "Canada",
    "Cyprus",
    "Dominica",
    "Eswatini",
    "Fiji",
    "Gambia",
    "Ghana",
    "Grenada",
    "Guyana",
    "India",
    "Jamaica",
    "Kenya",
    "Kiribati",
    "Lesotho",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Malta",
    "Mauritius",
    "Mozambique",
    "Namibia",
    "Nauru",
    "New Zealand",
    "Nigeria",
    "Pakistan",
    "Papua New Guinea",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Solomon Islands",
    "South Africa",
    "Sri Lanka",
    "Tanzania",
    "Tonga",
    "Trinidad and Tobago",
    "Tuvalu",
    "Uganda",
    "United Kingdom",
    "Vanuatu",
    "Zambia",
]

#opdracht 1
paspoort = {
    "pasfoto": "pasfoto.png",
    "achternaam": "vader",
    "voormaan": "darth",
    "geboortedatum": 10111990,
    "geboorteplaats": "Skaidy",
    "geslacht": "man",
    "lengte": 1.95,
    "handtekening": "hanttekening.png",
    "burgerservicenummer": 1234567890,
    "nationaliteit": all_countries[165],
    "vingerafdrukken": ["vingerafdruk001.png", "vingerafdruk002.png"]
    }

geboortedatum = paspoort["geboortedatum"]
lengte = paspoort["lengte"]
geboorteplaats = paspoort["geboorteplaats"]
nationaliteit = paspoort["nationaliteit"]

print("geboortedatum is:", geboortedatum,
      "lengte is:", lengte,
      "geboorteplaats is:", geboorteplaats,
      "nationaliteit is:", nationaliteit)

#opdracht 2
achternamen = [
    "vader",
    "skywalker",
    "solo",
    "palpatine",
    "kenobi"
    ]

voornamen = [
    "darth",
    "luke",
    "han",
    "rey",
    "obi-wan"
    ]

#jaar-maand-dag. dus 11 december 1990 = 19901211
geboortedatums = [
    19901211,
    20021215,
    19951714,
    20011111,
    20121212
    ]

lengtes = [
    1.84,
    1.90,
    2.01,
    2.15,
    1.55
    ]

burgerservicenummers = [
    1987654321,
    1357924680,
    1864297531,
    1111111111,
    6969696969
    ]

randompaspoort = {
    "pasfoto": "pasfoto.png",
    "achternaam": achternamen[2],
    "voormaan": voornamen[2],
    "geboortedatum": geboortedatums[4],
    "geboorteplaats": "Skaidy",
    "geslacht": "man",
    "lengte": lengtes[2],
    "handtekening": "hanttekening.png",
    "burgerservicenummer": burgerservicenummers[2],
    "nationaliteit": all_countries[12],
    "vingerafdrukken": ["vingerafdruk001.png", "vingerafdruk002.png"]
    }

print(randompaspoort)

#opdracht 3

#20020428 = 28 april 18 jaar terug
print("ouder dan 18 jaar:", randompaspoort["geboortedatum"] < 20020428)
print("nationalitijd in Gemenebest van Naties:", randompaspoort["nationaliteit"] in commonwealth_states)

randompaspoort["pasfoto"] = "nieuwePasfoto.png"

randompaspoort["vingerafdrukken"] = ["vingerafdruk001.png",
                                    "vingerafdruk002.png",
                                    "vingerafdruk003.png",
                                    "vingerafdruk004.png",
                                    "vingerafdruk005.png",
                                    "vingerafdruk006.png",
                                    "vingerafdruk007.png",
                                    "vingerafdruk008.png",
                                    "vingerafdruk009.png",
                                    "vingerafdruk000.png"]

print(randompaspoort)
